/**
 * fills_enriched - Enriched Fills with Markout (中核)
 *
 * Requirements: 9.1, 9.2, 9.3, 9.4, 9.5, 12.4
 * - Generated by summarizer from ex_fill
 * - Contains markout calculations at 1s/10s/60s
 * - Reference price is mid (9.2)
 */

import {
  index,
  integer,
  numeric,
  pgTable,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";

import { exFill } from "./ex-fill";

export const fillsEnriched = pgTable(
  "fills_enriched",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    fillId: uuid("fill_id")
      .notNull()
      .references(() => exFill.id),
    ts: timestamp("ts", { withTimezone: true, mode: "date" }).notNull(),
    exchange: text("exchange").notNull(),
    symbol: text("symbol").notNull(),
    side: text("side").notNull(),
    fillPx: numeric("fill_px").notNull(),
    fillSz: numeric("fill_sz").notNull(),

    // Reference prices at different time horizons
    midT0: numeric("mid_t0"),
    midT1s: numeric("mid_t1s"),
    midT10s: numeric("mid_t10s"),
    midT60s: numeric("mid_t60s"),

    // Markout in bps (sign consistent for BUY/SELL)
    markout1sBps: numeric("markout_1s_bps"),
    markout10sBps: numeric("markout_10s_bps"),
    markout60sBps: numeric("markout_60s_bps"),

    // Features at fill time
    spreadBpsT0: numeric("spread_bps_t0"),
    tradeImbalance1sT0: numeric("trade_imbalance_1s_t0"),
    realizedVol10sT0: numeric("realized_vol_10s_t0"),
    markIndexDivBpsT0: numeric("mark_index_div_bps_t0"),
    liqCount10sT0: integer("liq_count_10s_t0"),

    // Context
    state: text("state").notNull(),
    paramsSetId: uuid("params_set_id").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    index("fills_enriched_exchange_symbol_ts_idx").on(
      table.exchange,
      table.symbol,
      table.ts.desc(),
    ),
    index("fills_enriched_fill_id_idx").on(table.fillId),
  ],
);

export type FillsEnriched = typeof fillsEnriched.$inferSelect;
export type NewFillsEnriched = typeof fillsEnriched.$inferInsert;
